ci:
  build: .
  links:
    - postgres
  volumes_from:
    - ci_output
  command: ./ci.sh ci postgres

ci_output:
  image: alpine:3.3
  volumes:
    - /root/app/target
  command: /bin/sh

postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=mysecretpassword

db_init:
  build: ../ops
  volumes_from:
    - secret:ro
  links:
    - postgres
  command: bundle exec rake db:init[local_docker]

secret:
  image: my-ops-secret
  volumes:
    - /root/.ssh
